Feature/header
DamianJorga/aod pull request #3
Opened 2020-06-11 14:16 UTC by DamianJorga

finished header section please check when you have time :)

2020-06-11 17:34 UTC, greg-top requested changes
Hey troche zmian ogolnych do zrobienia wstawiam tutaj:
to fix:

**PR  jest zle ustawiony, powinien od merge kod do develop branch, w tym PR on merge kod do feature/initial-commit-not-finished. Wyedutuj swoj PR, nie usuwaj go :)**

**Wszystkie widoki:**
- linki menu sa zle rozlozone oraz style sa inne niz na design, porownaj sobie odstepy, kolory, wielkosc czcionki itp z PSD.
- nie dodales zadnego paddingu do nav i logo dotyka gornej krawedzi strony.
- przejscie tonalne miedzy menu a bannerem jest zbyt wyrazne. Trzeba bd jednak skorzystac z utworzenia gradientu na podstawie zdjecia :). Aby to zrobic:
1.) Wez wytnij 1px pasek o wysokosci nav (sam background), a nastepnie wczytaj go jako background image i powtorz przez caly wiersz:

#CSS (cos takiego mozesz uzyc)
  background-image: url("../image/header-gradient2.jpg");
  background-position: left;
  background-repeat: repeat-x;
  border-bottom: 1px solid #ccc;

2.)tam pewnie dalej nie bd zbyt dobre przejscie tonalne wiec dodaj jeszcze border-bottom w jakims dobrze dobranym kolorze szarosci aby odcinalo nav od banera (wiem ze tak nie jest w design ale czasami moozna to lekko nagiac)

**mobile:**
- menu nie moze byc jako lista linkow pod logo, trzeba utworzyc jakies menu mobilne, na poczatek moze to byc poprostu hamburger menu ktore wyswietli linki po kliknieciu. Zerknij sobie tutaj: https://www.w3schools.com/howto/howto_js_mobile_navbar.asp. Zastosuj hamburger menu dla mobile, mobile landscape oraz malego tabletu &#128125;

**mobile landscape**
- tutaj widac 2 zdjecia bannera w tym samym czasie, musisz ukryc jedno

**tablet**
- tutaj widac 2 zdjecia bannera w tym samym czasie, musisz ukryc jedno

**Moga sie tez pojawic wymagane zmiany jako komentarze w kodzie, wiec zerknij tez prosze &#128126;**

2020-06-11 17:58 UTC, greg-top requested changes
i zmiany jakie wylapalem w kodzie :)

2020-06-11 17:58 UTC, greg-top commented on index.html
> +                <img class="col-mobile-hide" src="image/logo.png" alt="Logo AOD">
w tym przypadku atrybut ALT powinien zostac pusty wedlug zalecen a11y (accessibility) poniewaz te zdjecie nie niesie ze soba zadnego przekazu, jest ono czysto dekoracyjne

2020-06-11 17:58 UTC, greg-top commented on index.html
> +            <img src="image/desktop-header.jpg" alt="">
Tutaj zostawiles pusty atrybut alt co jest dobra praktyka gdy grafika jest czysto dekoracyjna :). To jest szablon strony, wiec dopiero po wprowadzeniu tresci programista lub SEO manager zdecyduje o atrybucie alt :)

2020-06-11 17:58 UTC, greg-top commented on index.html
> +        </div>
Nie rozumiem dlaczego pojawil sie znowu nowy markup w tym PR, zrobiles go w ostatnim :). Czy jestes pewien ze zaktualizowales sobie develop branch lokalnie zanim utworzyles feature branch? Czy stworzyles feature branch za pomoca git flow?

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +// font-family: 'Lato', sans-serif;
te komentarze sa raczej oczywiste i mozna je usunac &#128126;

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +$font-First: 'Lato', sans-serif;
powinno byc $font-first jak cos :).

Jednak ja bym zrobill cos jeszcze. Zerknij ze wczytujesz 2 rodzaje fontow:
- sans-serif (bez ogonkow, jak wydrukowane)
- serif (tak zwane z ogonkami, te fonty wygladaja jakby ktos je pisal recznie)

nazwij sobie te zmienne odpowiednia:
$font-serif
$font-sans-serif

wiecej o fontach szeryfowych i bez szeryfa poczytasz tutaj: http://how2html.pl/czcionka-szeryfowa-bezszeryfowa/

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +// ###Color###
colors powinno byc :), ale chyba pominalbym ten komentarz calkowicie :)

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +$color-first: #f7f7f7;
tutaj nazwalbym to odpowiednio:

- color-primary
- color-secondary

albo odpowiednia tak jakie sa kolory, np:
- color-grey
- color-light-blue
- color-dark-red

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +    font-weight: bold;
teoretycznie jest to dozwolony zapis:

font-weight: bold, jednak zamienilbym go na wartosc liczbowa :)

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/global.scss
> +    font-weight: normal;
teoretycznie jest to dozwolony zapis:

font-weight: bold, jednak zamienilbym go na wartosc liczbowa :)

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/header.scss
> +    height: 100vh;
nie do konca jestem przekonany czy header powinien zajac 100% widoku mobile :). Wydaje mi sie ze nie, ale mozemy sprawdzic to pozniej jak dodasz kontent :)

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/header.scss
> +background-image: url("../image/bg-nav-header.jpg");
dodalem komentarz ogolny do PR. ogolnie jest zbyt silne przejscie tonalne, zerknij sobie na insttukcje ktore ci zostawilem w ogolnym komentarzu w PR

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/header.scss
> +background-image: url("../image/bg-nav-header.jpg");
wczytales zdjecie a nastepnie je rozciagnoles, nie jest to dobra praktyka poniewaz na duzych ekranach rozdzielczosc bd bardzo niska i tlo straci na jakosci

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/header.scss
> +@media (min-width: 768px){
postaraj sie uzywac takich samych brakpointow w media query jakie istnieja w simple-css-layout.css. W ten sposob masz 2 zestawy urzadzen responsywnych i bd ci sie style rozjezdzaly :). Najlepiej stworz sobie zmienne z breakpointammi:
$mobile: xxx px;
$mobile-landscape: yyy px;

2020-06-11 17:58 UTC, greg-top commented on src/sass/layout/header.scss
> +@media (min-width: 640px) and (orientation:landscape){
hmmm to media query jest napisane zle, postaraj sie uzyc breakpointow z pliku simple-css-layout

2020-06-11 17:58 UTC, greg-top commented on src/sass/mixins.scss
> +    content: " ";
mozna usunac spacje miedzy czudzyslowami, nie jest wymagana a zabierze exra 1 bajt pamieci za kazdym razem jak ja wykonasz ;)

2020-06-11 17:58 UTC, greg-top commented on src/sass/mixins.scss
> +  &:after{
czy mozesz wyjasnic jak dziala ta czesc kodu? Nie rozumiem jej

2020-06-12 18:22 UTC, DamianJorga commented
i haven't done the gradient yet and i hope everything else has improved

2020-06-12 19:08 UTC, greg-top commented
Czesc,

tutaj masz liste ogolna, zerknij tez na komentarze w kodzie, bo nie wszystko chyba znalazles:)

to fix:

**ALL VIEWS**
1.) linki menu sa zle rozlozone oraz style sa inne niz na design, porownaj sobie odstepy, kolory, wielkosc czcionki itp z PSD.
____________________
code review:
- tutaj dalej jest zle, zauwaz ze w twojej pracy linki menu sa rozlozone na calej szerokosci row, w projekcie sa one blizej logo i srodka strony
- musisz zwracac uwage na szczegoly, ostatnio wpisalem zebys zerknal na fonty w PSD, czcionka w PSD jest bezszeryfowa, u Ciebie szeryfowa :). Dodatkowo masz za duzy rozmiar czcionki i nie jestem do konca pewien czy kolor jest prawidlowy (sprawdz to dokladnie w PS)
==================================
2.) nie dodales zadnego paddingu do nav i logo dotyka gornej krawedzi strony.
__________________________________
code review:
- dodales padding od gory, ogolnie jestem zwolennikiem dodawania paddingu rowniez na dole aby optycznie content dla row byl wysrodkowany pionowo ;). Nie jest to bledem tak jak zrobiles jednak ciezko mi ocenic jak to wyglada ze wzgledu na niedokonczone zadanie z gradientem. Jak poprawisz gradient dla header zerknij czy nie potrzeba dodac pdding bottom :)
==================================
3.) przejscie tonalne miedzy menu a bannerem jest zbyt wyrazne. 
__________________________________
code review:
Do dokonczenia


**MOBILE:**
- hamburger menu dla mobile i tablet
________________________________
code review: 
dobra robota! :)


**MOBILE LANDSCAPE**
- tutaj widac 2 zdjecia bannera w tym samym czasie, musisz ukryc jedno
__________________________________
code review:
dobra robota!

**TABLET**
- tutaj widac 2 zdjecia bannera w tym samym czasie, musisz ukryc jedno
__________________________________
code review:
dobra robota!

2020-06-13 09:49 UTC, greg-top reviewed
Czesc, 
wymagane zmmiany w kodzie ponizej

2020-06-13 09:49 UTC, greg-top commented on index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
Mysle ze w tym tutorialu co ci go dalem to kazali skorzystac z font-awesome ikony :). Jest to jak najbardziej dobre rozwiazanie z punktu widzenia kodu.

Jednak w tym projekcie zastosowalismy tylko 1 ikonke z font-awesome (hamburger icon) co nie jest dobre z punktu widzenia optymalizacji strony, poniewaz:
- wczytujemy dodatkowy plik, czyli mamy dodatkowe zadanie serwera dla 1 ikony

Proponuje abys sciagnal sobie hamburger icon w postaci SVG (dla ikon jest to najlepsze rozwiazanie) lub png i usunal font-awesome z tego projektu :-)

2020-06-13 09:49 UTC, greg-top commented on index.html
> +                        <a href="#anout-us" class="nav-link">about us</a>
literowka,
powinno byc #about-us dla kotwicy

2020-06-13 09:49 UTC, greg-top commented on scripts/main.js
> +function myFunction() {
to jest stary sposob pisania js :). Mysle ze to sie pojawilo w tym tutorialu ktory ci dalem.

Jest tutaj kilka problemow niespelniajacych standaru ES2015 (i nowszych):
- utworzyles tutaj standardowa funkcje, ktora nastepnie wywolales jako parametr onclick w HTML. Tego typu rozwiazanie blokuje renderowanie HTMLa na stronie.
- uzyles starego typu deklaracji zmiennych slowem kluczowym var
- dodales zmiany w CSS za pomoca js, raczej powinienes dodac klase opened do eventu click na hamburger icon i ostylowac ja w pliku scss

Poprawnie napisany kod wyglada nastepujaco:

2020-06-13 09:49 UTC, greg-top commented on scripts/main.js
> +function myFunction() {
Dodatkowo plik ten powinien zostac dodany do folderu src/js a nastepnie zminimalizowany za pomoca zadania gulp i wygenerowany w tej lokalizacji :). Wiem, ze nie omowilismy porzadnie Gulpa dlaytego zrobimy to razem przy najbliszym week resume :)

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/global.scss
> +// ###Color###
dalej jest literowka do poprawy w komentarzu :)

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/global.scss
> +    font-weight: normal;
postaraj sie zmienic font-weight na wartosci liczbowe, prosze :). To takie troche moje zboczenie ale uwazam ze tak sie lepiej to widzi dla deva :)

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/header.scss
> +        color: black;
uzywanie nazw kolorow jak black, white, itp nie wyglada za dobrze w kodzie. Devsy uzywaja wartosci #HEX dla kolorow :). Zmien prosze to na #000;

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/header.scss
> +background-image: url("../image/bg-nav-header.jpg");
jak mowilismy, ta sekcja jest do dokonczenia

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/header.scss
> +background-image: url("../image/bg-nav-header.jpg");
jak mowilismy, ta sekcja jest do dokonczenia

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/header.scss
>      color: $color-third;
patrzac w kod nie mam pojecia co znaczy $color-third. Nazwa ta nie jest intuicyjna. Staraj sie uzywac nazw zmiennych, ktore opisuja ich zawartosc. W tym wypadku lepsza praltyka byloby okreslenie jaki kolor ma ta zmienna, np.:

$color-brown
$color-red

2020-06-13 09:49 UTC, greg-top commented on src/sass/layout/header.scss
> +  @media (min-width: 576px) and (orientation: landscape) {
wydaje mi sie ze mozesz usunac orientation: landscape :)

2020-06-13 09:49 UTC, greg-top commented on scripts/main.js
> +function myFunction() {
//musisz tez dokonac zmian w pliku html

//kod js
const button = document.querySelector(".mobile-menu_button");
button.addEventListener("click", mobileMenu);

function mobileMenu() {
  const mobileLinks = document.querySelector(".menu-mobile");
  mobileLinks.classList.toggle("opened");
}

2020-06-16 09:26 UTC, DamianJorga commented
hej hej, mam nadzieje ze tym razem wszystko znalazlem i poprawilem :)  z bgc nie zrobilem tak jak polecales poniewaz jesli tak robilem wychodzil mi jeden kolor, na mobile jeszcze chyba delikatnie widac to ale jest lepiej :) na desktopie wydaje mi sie ze juz jest dobrze. wczesniej bylo bardzo widoczne poniewaz zle powycinalem grafiki ( wycielem pasek dla Nav ale juz nie usunelem tego paska z dolnej grafiki)

2020-06-16 09:28 UTC, DamianJorga commented on css/simple-css-layout.css
nie odkomentowalem przepraszam

2020-06-16 17:22 UTC, greg-top approved these changes
wszystko w porzadku :)
dobra robota!

Mozesz zrobic merge to develop branch i otworzyc nowy feature branch do dalszej pracy (pamietaj aby zaktualizowac lokalna develop branch zanim utworzysz nowy feature branch)

2020-06-16 17:29 UTC, merged